codecov:
  require_ci_to_pass: false
  branch: main

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

comment:
  layout: "reach,diff,flags,tree,betaprofiling"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  branches:
    - main

# Enable test result processing
cli:
  plugins:
    pycoverage:
      report_type: "json"